### ISSUE TITLE
Unset values  in Dynamic CSS

### ISSUE THREAD

**Issue by eturi** [valendesigns/option-tree#359] opened 2014-07-02 20:30 UTC
Hi Derek.

I'm using theme version of OptionTree. I have a text field to set max-width of website's external div that acts as a wrapper. In a CSS field, having this CSS style:

.wrapper { 
     max-width:{{wrapper_max_width|1180}}px;
}

When installed the theme the first time, this field does not have any value, and the css shows an error:

.wrapper {  max-width:px; }

So it's not getting the default value. A bug maybe ?, what am I doing wrong ?

regards...

**Comment by valendesigns** [comment] 2015-02-08 04:21
Sorry for the long delay, but I can't reproduce this issue. If the theme options have not been saved, but the theme gets activated there should not be anything saved in `dynamic.css` at this point. Once the user hits save the file is then updated. I'm not sure why you are doing the following `{{wrapper_max_width|1180}}`. The parser does not except default values. The pipe is used to grab a value from within an array, by supplying a specific key where that value is saved. In any case, I can't reproduce this and will need more information to troubleshoot. Closing for now.

**Closed by valendesigns** 2015-02-08 04:21 UTC
