### ISSUE TITLE
OT 2.5.0

### ISSUE THREAD

**Issue by satrya** [valendesigns/option-tree#442] opened 2015-02-01 15:38 UTC
Hi @valendesigns 
I just started new theme project and would like to use OT 2.5.0, because the theme check issue in version 2.4.6. Does this version is stable?

By the way, when you'll release this version?

Thank you.

**Comment by valendesigns** [comment] 2015-02-03 04:28
Duplicate of #410

**Closed by valendesigns** 2015-02-03 04:28 UTC
