### ISSUE TITLE
Select Field is not working in the new update. 

### ISSUE THREAD

**Issue by sabbirk15** [valendesigns/option-tree#494] opened 2015-04-12 17:32 UTC
Hello There,

I found that the select fields is not working properly in the new update. Specially with page or post select. When you select a page from the drop down it is not showing. Once you update the settings then you can can see what you just saved. Even you can change the select item easily without problem.

So the problem basically involves with new items or for the first time you are going to select a item from the drop down list.

Thanks
Sabbir H

**Comment by valendesigns** [comment] 2015-04-12 17:59
I didn't change anything to do with the select in the last update, but I'll check when I get back home in a couple hours.

**Comment by sabbirk15** [comment] 2015-04-12 18:32
Thanks for your reply. I think I checked with 2.4.x version. On that version it was working but in the latest version it is not working.

Hope this helps :)

**Comment by valendesigns** [comment] 2015-04-12 19:40
I checked and cannot reproduce the issue. Can you hard refresh your browser to clear the cache and see if the file was holding on to the old version?

**Comment by sabbirk15** [comment] 2015-04-12 19:51
I am away from my office. I will make a development environment on my
server and will get you access by tomorrow.

I experienced this problem on several of websites both clients and mine. So
hard refresh will not work.

Please let me know on which email i should send you login details?

Regards
Sabbir

**Comment by valendesigns** [comment] 2015-04-12 20:02
Send it to derek@valendesigns.com

**Comment by sabbirk15** [comment] 2015-04-13 14:10
Sorry, I am off today. I will get you sever access by tomorrow :(

**Comment by Hendrik** [comment] 2015-04-14 17:25
I've noticed the same problem on a metabox select field within an item list.
The ```<span>``` content above the actual ```<select>``` item no longer changes when you select a different option (just selecting a different option without saving the changes), which is why the displayed value no longer updates on select.

**Comment by sabbirk15** [comment] 2015-04-14 17:33
Yap I have noticed it. I was trying to fix it from my end. Actually it
works but the visual appearance gives you a false impression that it does
not work. I wanted to set up a demo server for buddy Derek. But I did not
get chance yet.

Warm Regards,
Sabbir H

WpMania.Net <http://wpmania.net/Store/>
RewardThemes.Com <http://rewardthemes.com/store/>
SabbirH.Com <http://sabbirh.com>

Ofc: +88 0176 568 3191
Skype: wp_developer
Facebook: https://www.facebook.com/TheWpDeveloper

------------------------------------------------------------------------

*CONFIDENTIALITY STATEMENT*: All information included in this
communication, including attachment(s), is intended solely for delivery to
and authorized use by the addressee(s) identified above, and may contain
privileged, confidential, proprietary and/or trade secret information
entitled to protection and/or exempt from disclosure under applicable law.
If you are not the intended recipient, please note that any use,
distribution or copying of this communication is unauthorized and may be
unlawful. If you have received this communication in error, please notify
sender immediately and delete this communication from your computer.

**Comment by sabbirk15** [comment] 2015-04-14 17:33
Yap I have noticed it. I was trying to fix it from my end. Actually it works but the visual appearance gives you a false impression that it does not work. I wanted to set up a demo server for buddy Derek. But I did not get chance yet.

**Comment by Hendrik** [comment] 2015-04-14 17:42
Reverting one of the v2.5.2 changes fixes the issue, at least for my metabox item list select field.
Line 590 in assets/js/ot-admin.js : https://github.com/valendesigns/option-tree/blob/master/assets/js/ot-admin.js#L590

I changed it from
```$('.option-tree-ui-select').on('change', function () {```
to the previous v2.5.1 code
```$(document).on('change', '.option-tree-ui-select', function () {```
and the change event started firing again. I assume it could be an issue with the dynamically loaded item list, so that the change event doesn't get attached to the select box in those.

**Comment by sabbirk15** [comment] 2015-04-17 08:52
Hello Derek,

I sent you a pull request with the fixes for this issue here https://github.com/valendesigns/option-tree/pull/496

I am new at github but I feel I am will be using it a lot :)

Regards
Sabbir

**Comment by valendesigns** [comment] 2015-04-17 10:22
I'll merge it tomorrow and test then release a hotfix on Monday with any other minor things I find over the weekend. Also, what browser are you using because this isn't an issue with any of mine? I assume it's IE?

**Comment by sabbirk15** [comment] 2015-04-17 10:33
I checked the issue with all the Browser. You will not see the problem with a existing select field. Once you set up a new website and will try to select a option for a select drop down you will see the values will not changed. Once you save the settings for the first time you will see it works fine. 

You will suffer more if you use select option within a list item. As each time you add a new list the select fields will not visible until you save the settings. @Hendrik pointed out what is really happening there https://github.com/valendesigns/option-tree/issues/494#issuecomment-92992921. 

Buddy, I mainly use Crome :)

I would love to get the new hot fix :)

**Comment by valendesigns** [comment] 2015-04-17 10:40
Makes sense. It will be patched and available on Monday for sure. Cheers!

**Comment by BassemN** [comment] 2015-04-17 11:50
I have the same issue with select dropdowns.

**Comment by valendesigns** [comment] 2015-04-20 23:54
The pull request has been merged and v2.5.4 will be released in a couple hours after I figure out the best way to handle term slitting in WordPress 4.2. Thanks guys!

**Closed by valendesigns** 2015-04-20 23:54 UTC
